root="."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ."
#  Binary file yields from `cmd`.
bin = "tmp/main"

# 80番ポートで起動するように実行引数を指定
full_bin = "APP_ENV=dev APP_USER=air ./tmp/main 80"

include_ext = ["go", "tmp", "tmpl", "html"]
exclude_dir = ["asserts", "tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go]
exclude_unchanged = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 #ms

[log]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true